### ISSUE TITLE
Browser Chat functionality for an agent instead of a trained model

### ISSUE THREAD

**Issue by VishalPallagani** [facebookresearch/ParlAI#3725]
I have read the docs where an example of using a blender_90M model is given. However, I am trying to understand how I can give an agent that I have developed (it is not a trained model, it is merely an agent programmed to do a particular logical task or for simplicity consider any agent - such as [FixedResponse](https://github.com/facebookresearch/ParlAI/tree/master/parlai/agents/fixed_response)). I am unable to figure out how can I add such an agent to the models parameter of the config file as shown in the docs - 
```
  models:
    blender_90M:
      model: transformer/generator
      model_file: zoo:blender/blender_90M/model
      interactive_mode: True
      no_cuda: True
```

Any help will be greatly appreciated. Thanks in advance.

**Comment by klshuster** [comment]
the `models` key is just a mapping from `agent_name` to it's various command line / opt parameters.

if you have an agent developed that you can access via `--model my_custom_agent`, you can specify it via the following:

```
  models:
    my_agent_key:
      model: my_custom_agent
      custom_agent_flag1: custom_agent_flag1_value
```

if you change `blender_90M` to `my_agent_key`, you'll also need to change the `MODEL_KEY` here: https://github.com/facebookresearch/ParlAI/blob/master/parlai/chat_service/tasks/chatbot/worlds.py#L34 (and in similar places for other tasks)

Sorry for the late response; let me know if that helps!
