### ISSUE TITLE
BlenderBot2 adds wrong prefix when storing memories at runtime

### ISSUE THREAD

**Issue by fraferra** [facebookresearch/ParlAI#4292]
**Bug description**
BB2 currently is storing memories and facts about the human chatter with the prefix `partner's persona` even though it was trained `partner`s persona` prefix to be associated with the bot and `your persona` prefix to be associated to a human chatter

**Expected behavior**
Viewing memory logs being associated to `your persona` rather than `partner's persona`

**Logs**
Chat history:
```
        HUMAN: "hi",
        BOT: "Hi! How are you?",
        HUMAN:"i like pizza",
         BOT: "What kind of pizza do you like? ",
        HUMAN:"i like pepperoni",
         BOT: "What’s your favorite toppings? ,
        HUMAN: "i like cheese as a topping. u?",
         BOT: "I’m not sure I’ve ever had a cheese topping. I’ll have to give it a try!",
        HUMAN: "what did you try?",
         BOT: "It’s been a while, but I remember liking it when I was a kid",
        HUMAN: "i have eaten pizza recently",
```

Memory logs:
```
[I 220106 22:34:11 sub_modules:328] raw memories: ['I like ice cream. I have eaten pizza recently.']
[I 220106 22:34:11 sub_modules:358] 0 : I like ice cream. I have eaten pizza recently.
[I 220106 22:34:11 sub_modules:331] memories to write: ["partner's persona: I like ice cream. I have eaten pizza recently."]
[I 220106 22:34:11 sub_modules:334] Writing memories: partner's persona: I like ice cream. I have eaten pizza recently.
[I 220106 22:34:11 modules:345] Classify Retrieval: 0.65
[I 220106 22:34:11 modules:384] Search Complete: 0.65
[I 220106 22:34:11 modules:726] Writing [1] memories
[I 220106 22:34:11 modules:616] Write Memory Complete: 0.01
[I 220106 22:34:11 modules:622] Memory Retrieval Complete: 0.02
[I 220106 22:34:11 modules:624] memories: [[ID:
    Title:
    Text: partner's persona : i like ice cream. i have eaten pizza recently., ID:
    Title:
    Text: , ID:
    Title:
    Text: , ID:
    Title:
    Text: , ID:
    Title:
    Text: ]]
[I 220106 22:34:11 modules:626] Reading from Memory
[I 220106 22:34:11 modules:395] Memory Access Complete: 0.67```
```

**Additional context**
Current config for model:
```
models:
    blenderbot2:
      model: projects.blenderbot2.agents.blenderbot2:BlenderBot2RagAgent
      model_file: data/models/bb2_persona_filtered_3/model
      interactive_mode: True
      no_cuda: False
      override:
        rag_model_type: sequence
        memory_decoder_ignore_phrase: "persona:"
        memory_decoder_key: full_text
        memory_decoder_model_file: zoo:blenderbot2/memory_decoder/model
        memory_key: full_text
        memory_decoder_delimiter: '\n'
        memory_writer_model: bert
        memory_decoder_truncate: -1
        memory_doc_delimiter: ':'
        memory_doc_title_delimiter: ' / '
        memory_extractor_phrase: full_text
        search_server: relevant_search_server
        interactive_mode: True
        topk: 10
        beam_size: 10
        topp: 0.8
        fp_16: True
        fp16_impl: mem_efficient
        use_memories: True
        query_generator_beam_min_length: 2
        query_generator_beam_size: 1
        query_generator_delimiter: '\n'
        query_generator_ignore_phrase: 'persona:'
        query_generator_inference: beam
        query_generator_key: full_text
        query_generator_model_file: zoo:blenderbot2/query_generator/model
        query_generator_truncate: -1
        query_model: bert_from_parlai_rag
        rag_retriever_query: full_history
        skip_generation: False
        include_personas: False
```

Thank you!
