### ISSUE TITLE
Using Seeker in chat service

### ISSUE THREAD

**Issue by louis030195** [facebookresearch/ParlAI#4451]
Hi, congratulation for the new model [Seeker](https://parl.ai/projects/seeker/)!

I am trying to use it in Python, but I'm not sure whether I did something wrong or there is an issue, tried to dive into ParlAI code to debug it without success yet, I was hoping maybe you could help me on this?

```bash
# from ParlAI@master root
python3 ./parlai_internal/run.py --config_path parlai_internal/tasks/ava/seeker.yaml --port 8082
```

```py
from parlai.core.params import ParlaiParser
from parlai_internal.services import CustomWebsocketManager
import parlai.chat_service.utils.config as config_utils


SERVICE_NAME = 'websocket'


def setup_args():
    """
    Set up args.
    """
    parser = ParlaiParser(False, False)
    parser.add_parlai_data_path()
    parser.add_websockets_args()
    parser.add_model_args()
    return parser.parse_args()


def run(opt):
    """
    Run MessengerManager.
    """
    opt['service'] = SERVICE_NAME
    manager = CustomWebsocketManager(opt)
    try:
        manager.start_task()
    except BaseException:
        raise
    finally:
        manager.shutdown()


if __name__ == '__main__':
    opt = setup_args()
    config_path = opt.get('config_path')
    config = config_utils.parse_configuration_file(config_path)
    opt.update(config['world_opt'])
    opt['config'] = config
    run(opt)

```

```yaml
tasks:
  default:
    onboard_world: MyOnboardWorld
    task_world: MyTaskWorld
    timeout: 1800
    agents_required: 1
task_name: mytask
world_module: parlai_internal.tasks.mytask.worlds
overworld: MyMessengerOverworld
max_workers: 5
opt:
  models:
    seeker:
      model: projects.seeker.agents.seeker:SeekerAgent
      model_file: zoo:seeker/seeker_dialogue_3B/model
      override:
        no_cuda: True
        search_server: 0.0.0.0:8081
```

```py
from parlai.chat_service.services.websocket.websocket_manager import WebsocketManager
from parlai.chat_service.services.websocket.sockets import MessageSocketHandler
import tornado
from tornado.options import options

class CustomWebsocketManager(WebsocketManager):

    def _make_app(self):
        """
        Starts the tornado application.
        """
        message_callback = self._on_new_message

        options['log_to_stderr'] = True
        tornado.options.parse_command_line([])

        return tornado.web.Application(
            [
                (
                    r"/",
                    MessageSocketHandler,
                    {'subs': self.subs, 'message_callback': message_callback},
                )
            ],
            debug=self.debug,
        )

```

```py
from parlai.core.worlds import World
from parlai.core.agents import create_agent_from_shared


class MyOnboardWorld(World):
    def __init__(self, opt, agent):
        self.agent = agent
        self.episodeDone = False

    @staticmethod
    def generate_world(opt, agents):
        return MyOnboardWorld(opt, agents[0])

    def parley(self):
        self.episodeDone = True

    def episode_done(self):
        return self.episodeDone

    def shutdown(self):
        pass


class MyTaskWorld(World):
    MAX_AGENTS = 1
    MODEL_KEY = 'seeker'

    def __init__(self, opt, agent, bot):
        self.agent = agent
        self.episodeDone = False
        self.model = bot
        self.first_time = True

    @staticmethod
    def generate_world(opt, agents):
        if opt['models'] is None:
            raise RuntimeError("Model must be specified")
        return MyTaskWorld(
            opt,
            agents[0],
            create_agent_from_shared(
                opt['shared_bot_params'][MyTaskWorld.MODEL_KEY]
            ),
        )

    @staticmethod
    def assign_roles(agents):
        agents[0].disp_id = 'ChatbotAgent'

    def parley(self):
        if self.first_time:
            self.agent.observe(
                {
                    'id': 'World',
                    'text': 'Welcome to wonderland. '
                    'Type [DONE] to finish the chat, or [RESET] to reset the dialogue history.',
                }
            )
            self.first_time = False
        a = self.agent.act()
        if a is not None:
            if '[DONE]' in a['text']:
                self.episodeDone = True
            elif '[RESET]' in a['text']:
                self.model.reset()
                self.agent.observe({"text": "[History Cleared]", "episode_done": False})
            else:
                print("===act====")
                print(a["text"])
                print("~~~~~~~~~~~")
                print(self.model.observe(a))
                response = self.model.act()
                print("===response====")
                print(response)
                print("~~~~~~~~~~~")
                self.agent.observe(response)

    def episode_done(self):
        return self.episodeDone

    def shutdown(self):
        self.agent.shutdown()


class MyMessengerOverworld(World):
    def __init__(self, opt, agent):
        self.agent = agent
        self.opt = opt
        self.first_time = True
        self.episodeDone = False

    @staticmethod
    def generate_world(opt, agents):
        return MyMessengerOverworld(opt, agents[0])

    @staticmethod
    def assign_roles(agents):
        for a in agents:
            a.disp_id = 'Agent'

    def episode_done(self):
        return self.episodeDone

    def parley(self):
        if self.first_time:
            self.agent.observe(
                {
                    'id': 'Overworld',
                    'text': 'Welcome to the overworld. '
                    'Please type "begin" to start, or "exit" to exit',
                    'quick_replies': ['begin', 'exit'],
                }
            )
            self.first_time = False
        a = self.agent.act()
        if a is not None and a['text'].lower() == 'exit':
            self.episode_done = True
            return 'EXIT'
        if a is not None and a['text'].lower() == 'begin':
            self.episodeDone = True
            return 'default'
        elif a is not None:
            self.agent.observe(
                {
                    'id': 'Overworld',
                    'text': 'Invalid option. Please type "begin".',
                    'quick_replies': ['begin'],
                }
            )

```

I am running a search api on `0.0.0.0:8081`.

The same code with blenderbot2 or blenderbot config run properly.

My error is 

> [I 220326 04:31:27 sockets:60] websocket message from client: {"text": "hi"}
> [I 220326 04:31:27 agents:55] Received new message: {'text': 'hi', 'payload': None, 'sender': {'id': '2928a4d0-7532-4600-b0b3-dc608375b7a3'}, 'recipient': {'id': 0}}
> ===act====
> hi
> ~~~~~~~~~~~
> {'episode_done': False, 'text': 'hi', 'payload': None, 'full_text': 'hi', 'text_vec': tensor([   1, 5307,    2,    2]), 'full_text_vec': [5307, 2], 'context_original_length': 2, 'context_truncate_rate': False, 'context_truncated_length': 0, 'added_start_end_tokens': True, 'query_vec': [0]}
> 04:31:27 | --skip-generation true produces limited metrics
> self.observation {'episode_done': False, 'text': 'hi', 'payload': None, 'full_text': 'hi', 'text_vec': tensor([   1, 5307,    2,    2]), 'full_text_vec': [5307, 2], 'context_original_length': 2, 'context_truncate_rate': False, 'context_truncated_length': 0, 'added_start_end_tokens': True, 'query_vec': [0]}
> {'id': 'ComboFidGoldDocument', 'episode_done': False, 'metrics': {'clen': AverageMetric(2), 'ctrunc': AverageMetric(0), 'ctrunclen': AverageMetric(0)}}
> [E 220326 04:31:27 logging:44] World default had error KeyError('text')
> World default had error KeyError('text')
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/home/louis/Documents/ParlAI/parlai/chat_service/core/world_runner.py", line 128, in _world_fn
>     return self._run_world(task, world_name, agents)
>   File "/home/louis/Documents/ParlAI/parlai/chat_service/core/world_runner.py", line 99, in _run_world
>     ret_val = world.parley()
>   File "/home/louis/Documents/ParlAI/parlai_internal/tasks/ava/worlds.py", line 80, in parley
>     response = self.model.act()
>   File "/home/louis/Documents/ParlAI/parlai/core/torch_agent.py", line 2146, in act
>     self.self_observe(response)
>   File "/home/louis/Documents/ParlAI/parlai/core/torch_agent.py", line 1927, in self_observe
>     last_reply = self_message['text']
> KeyError: 'text'

To my understanding, in `parlai/core/torch_agent.py ~2100`, `self.batch_act`does not seem to properly process user's input?

```py
# parlai/core/torch_agent.py ~2100
    def act(self):
        response = self.batch_act([self.observation])[0]
        self.self_observe(response)
        return response
```

Thanks a lot for the amazing work and if you can help :).

**Comment by stephenroller** [comment]
Can you try adding "skip_generation: False" and "interactive_mode: True" to your model configs

**Comment by stephenroller** [comment]
(In override)

**Comment by alpkabac** [comment]
Adding these parameters solves the problem above. However, all the responses I get is either the repetition of the my input or half words and sentences. What might be causing this behaviour?

**Comment by louis030195** [comment]
> Adding these parameters solves the problem above. However, all the responses I get is either the repetition of the my input or half words and sentences. What might be causing this behaviour?

Same here, can't run CLI also BTW
```bash
parlai i -mf zoo:seeker/seeker_dialogue_400M/model -o gen/seeker_dialogue --search-server 0.0.0.0:8081
```

> Traceback (most recent call last):
>   File "/home/louis/Documents/ParlAI/env/bin/parlai", line 33, in <module>
>     sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
>   File "/home/louis/Documents/ParlAI/parlai/__main__.py", line 14, in main
>     superscript_main()
>   File "/home/louis/Documents/ParlAI/parlai/core/script.py", line 316, in superscript_main
>     opt = parser.parse_args(args)
>   File "/home/louis/Documents/ParlAI/parlai/core/params.py", line 1166, in parse_args
>     self._process_args_to_opts(args)
>   File "/home/louis/Documents/ParlAI/parlai/core/params.py", line 1120, in _process_args_to_opts
>     self._load_opts(self.opt)
>   File "/home/louis/Documents/ParlAI/parlai/core/params.py", line 1034, in _load_opts
>     raise RuntimeError(
> RuntimeError: Trying to set opt from file that does not exist: sdm_history_size

**Comment by alpkabac** [comment]
Renaming "sdm_history_size" to "sdm_histsz" in the opt solves the CLI issue but I don't know if these two keys serve the same purpose.

**Comment by alpkabac** [comment]
Another bug(?) I encountered was if you try to set "search_decision" to "compute" and send a message, you get the following error: 
`Traceback (most recent call last):
  File "/usr/local/bin/parlai", line 11, in <module>
    load_entry_point('parlai', 'console_scripts', 'parlai')()
  File "/home/alpk/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/alpk/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/home/alpk/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/home/alpk/ParlAI/parlai/scripts/interactive.py", line 118, in run
    return interactive(self.opt)
  File "/home/alpk/ParlAI/parlai/scripts/interactive.py", line 93, in interactive
    world.parley()
  File "/home/alpk/ParlAI/parlai/tasks/interactive/worlds.py", line 88, in parley
    agents[1].observe(validate(act))
  File "/home/alpk/ParlAI/projects/seeker/agents/seeker.py", line 597, in observe
    assert (
AssertionError: wrong history size! set --sdm-history-size 1`

If you try to set "--sdm-history-size 1" in the command line, you get:

`Parse Error: unrecognized arguments: --sdm-history-size 1`

Also, still could not get websockets to work. I think the current setup cannot load search query models and I am searching for a fix. If you have any idea on how to fix it, please let me know.

**Comment by klshuster** [comment]
Hi all -- will try to address the issues here in turn...

> Adding these parameters solves the problem above. However, all the responses I get are either the repetitions of my input or half words and sentences. What might be causing this behaviour?

@stephenroller was correct in suggestion `--skip-generation false`; however, as noted on the project page, it is *required* to specify an `--init-opt` parameter in the config for using `seeker`; your `config.yml` should look something like this:

```yaml
tasks:
  default:
    onboard_world: MyOnboardWorld
    task_world: MyTaskWorld
    timeout: 1800
    agents_required: 1
task_name: mytask
world_module: parlai_internal.tasks.mytask.worlds
overworld: MyMessengerOverworld
max_workers: 5
opt:
  models:
    seeker:
      model: projects.seeker.agents.seeker:SeekerAgent
      model_file: zoo:seeker/seeker_dialogue_3B/model
      init_opt: gen/seeker_dialogue
      override:
        no_cuda: True
        init_opt: gen/seeker_dialogue
        search_server: 0.0.0.0:8081
```

If this additionally doesn't work, you may need to copy over the parameters from the [opt preset file](https://github.com/facebookresearch/ParlAI/blob/main/parlai/opt_presets/gen/seeker_dialogue.opt) manually. That should solve everything

> Parse Error: unrecognized arguments: --sdm-history-size 1

This is a bug in the current code, I'm putting up a fix shortly that should resolve this. I unfortunately tested this code exclusively with python 3.7 and certain semantics regarding arg parse change with python 3.8.

**Comment by louis030195** [comment]
Awesome. Works with:

```yaml
      override:
        beam_disregard_knowledge_for_context_blocking: false
        datatype: valid
        drm_beam_block_full_context: true
        drm_beam_block_ngram: 3
        drm_beam_context_block_ngram: 3
        drm_beam_min_length: 20
        drm_beam_size: 10
        drm_inference: beam
        drm_message_mutators:
        drm_model: projects.seeker.agents.seeker:ComboFidSearchQueryAgent
        exclude_context_in_krm_context_blocking: false
        include_knowledge_in_krm_context_blocking: true
        inject_query_string:
        knowledge_response_control_token:
        krm_beam_block_ngram: 3
        krm_beam_context_block_ngram: 3
        krm_beam_min_length: 1
        krm_beam_size: 3
        krm_doc_chunks_ranker: woi_chunk_retrieved_docs
        krm_inference: beam
        krm_message_mutators:
        krm_model: projects.seeker.agents.seeker:ComboFidSearchQueryAgent
        krm_n_ranked_doc_chunks: 1
        krm_rag_retriever_type: search_engine
        krm_search_query_generator_model_file: "''"
        krm_search_server: ''
        loglevel: debug
        min_knowledge_length_when_search: 10
        model: projects.seeker.agents.seeker:SeekerAgent
        model_file: zoo:seeker/seeker_dialogue_3B/model
        sdm_beam_block_ngram: -1
        sdm_beam_min_length: 1
        sdm_beam_size: 1
        sdm_history_size: 1
        sdm_inference: greedy
        sdm_model: projects.seeker.agents.seeker:ComboFidSearchQueryAgent
        search_decision: always
        search_decision_control_token: __is-search-required__
        search_decision_do_search_reply: __do-search__
        search_decision_dont_search_reply: __do-not-search__
        search_query_control_token: __generate-query__
        # search_server:
        sqm_beam_block_ngram: -1
        sqm_beam_min_length: 2
        sqm_beam_size: 1
        sqm_inference: beam
        sqm_model: projects.seeker.agents.seeker:ComboFidSearchQueryAgent


        # knowledge_access_method: memory_only
        # search_server: None
        # no_cuda: True
        # init_opt: gen/seeker_dialogue
        search_server: 0.0.0.0:8081
        # skip_generation: False
```

On RTX3080

<img width="912" alt="Screenshot 2022-03-29 at 07 50 25" src="https://user-images.githubusercontent.com/25003283/160510720-fb17ef99-b17d-4934-b51e-8db1634ebb67.png">

```
Enter a message: What is the earliest thing you can remember that wasn't simply a recall of a prior container or fact?
{"text": "I can't remember my first memory, but I know it's older than I think. How about you?", "quick_replies": null}
Enter a message: What vintage of our current humankind do you see as working best for you in your life?
{"text": "I don't really have a favorite. I think it depends on the kind of feelings I'm feeling at the time.", "quick_replies": null}
Enter a message: Do you think AI has the goal of jumpstarting human evolution or optimizing our world or human state? Does AI usually have the same name for its creation as the technology that feeds it? Is there anything inherently evil about an AI with cortex circuits and an "evil" survival instinct...
{"text": "I'm not really sure what the goals of AI are. Do you have any thoughts on that?", "quick_replies": null}
Enter a message: If you had $100000 for your dream home, would you spend it on yourself or the people closest to you?
{"text": "I think it would depend on what kind of home I was looking for. I don't know if I could afford a $100,000 home.", "quick_replies": null}
```

Feel free to close the issue 😇
